INSERT OR REPLACE INTO franchises (id, name, description) VALUES ('naruto', 'Naruto', NULL);
INSERT INTO franchise_watch_order (franchise_id, step_order, title, type, episodes, anime_id, note) VALUES ('naruto', 1, 'Naruto (Original)', 'TV Series', '220 Episodes (Skip fillers 136–219)', NULL, 'The foundational original series covering Part 1.');
INSERT INTO franchise_watch_order (franchise_id, step_order, title, type, episodes, anime_id, note) VALUES ('naruto', 2, 'Naruto Shippuden (Episodes 1–175)', 'TV Series', 'Episodes 1–175', 'naruto-shippuden', 'From Kazekage Rescue through the Pain Assault arc.');
INSERT INTO franchise_watch_order (franchise_id, step_order, title, type, episodes, anime_id, note) VALUES ('naruto', 3, 'The Lost Tower (Movie)', 'Movie', '85 mins', NULL, 'Optional canon-friendly movie best enjoyed after episode 175.');
INSERT INTO franchise_watch_order (franchise_id, step_order, title, type, episodes, anime_id, note) VALUES ('naruto', 4, 'Naruto Shippuden (Episodes 176–493)', 'TV Series', 'Episodes 176–493', 'naruto-shippuden', 'Five Kage Summit and Fourth Great Ninja War.');
INSERT INTO franchise_watch_order (franchise_id, step_order, title, type, episodes, anime_id, note) VALUES ('naruto', 5, 'The Last: Naruto the Movie', 'Movie', '112 mins', NULL, 'MANDATORY CANON. Watch between Shippuden episodes 493 and 494.');
INSERT INTO franchise_watch_order (franchise_id, step_order, title, type, episodes, anime_id, note) VALUES ('naruto', 6, 'Naruto Shippuden (Episodes 494–500)', 'TV Series', 'Episodes 494–500', 'naruto-shippuden', 'The epilogue wedding arc leading directly into the next generation.');
INSERT INTO franchise_watch_order (franchise_id, step_order, title, type, episodes, anime_id, note) VALUES ('naruto', 7, 'Boruto: Naruto Next Generations', 'TV Series', '293 Episodes', NULL, 'Sequel series following the offspring of the Hidden Leaf heroes.');
INSERT OR REPLACE INTO anime (
      id, slug, title, original_title, year, episodes, status,
      personal_rating, poster, backdrop, added_date, last_updated,
      honesty_status, filler_percentage, trending, synopsis,
      franchise_id, franchise_step_order,
      review_heading, review_paragraphs,
      source_title, source_original_title, source_author, source_type,
      source_volumes, source_publication_status, source_adaptation_status,
      source_coverage, source_notes,
      power_system_name, power_system_paragraphs,
      lesson_heading, lesson_takeaway
    ) VALUES (
      'naruto-shippuden', 'naruto-shippuden', 'Naruto Shippuden', 'NARUTO -ナルト- 疾風伝', 2007, 500, 'Finished Airing',
      9, 'https://image.tmdb.org/t/p/w780/kV27gZqdaUQmFO3m6rEcvEpWzZN.jpg', 'https://image.tmdb.org/t/p/w1280/vIjyK706i8qfU3556gVvJ8Z8V6X.jpg', 'Jan 10, 2024', 'Nov 02, 2024',
      'watched', 41, 1, 'Naruto returns to the Hidden Leaf village after two and a half years of rigorous training with Jiraiya, facing the emerging threat of the shadowy Akatsuki syndicate seeking the Nine-Tailed Fox.',
      'naruto', 2,
      'A Generational Epic That Truly Demands a Filler Guide', '["If you cut out the 41% filler bloat, Naruto Shippuden is one of the most emotionally devastating and rewarding fantasy stories ever told. When it hits, nothing else in battle shonen comes close — the fight between Kakashi and Obito in the Kamui dimension is still peak anime choreography, and the emotional payoff of Naruto confronting Pain after the village destruction genuinely made me tear up.","That being said, the pacing in the final war arc can test your patience even when you skip the filler episodes, with constant flashback repetitions mid-fight. But the core story, Yasuharu Takanashi’s unforgettable soundtrack, and the ideological clashes make it an absolute triumph that I find myself rewatching every few years."]',
      'Naruto', 'NARUTO -ナルト-', 'Masashi Kishimoto', 'Manga',
      '72 Volumes / 700 Chapters', 'Completed (1999 – 2014)', 'Fully Adapted',
      'Anime adapts Chapters 245 through 700. The original pre-Shippuden series adapted Chapters 1 to 244.', 'Light novel epilogues (Kakashi Hiden, Shikamaru Hiden, Sasuke Shinden) were adapted into episodes 484–500.',
      'Chakra & Ninjutsu System', '["The power system of Naruto is grounded in Chakra — a mystical energy generated by blending physical energy gathered from every cell in the body with spiritual energy gained through study and experience. Once shaped through hand seals, chakra can be manifested into Ninjutsu (elemental attacks), Genjutsu (illusions targeting the nervous system), or Taijutsu (enhanced martial arts).","Advanced practitioners manifest Nature Transformations across five basic elements: Fire, Wind, Lightning, Earth, and Water. The rare fusion of two distinct natures simultaneously gives birth to Kekkei Genkai (bloodline traits such as Ice or Wood Release), while Kekkei Tota combines three elements into devastating Particle Style.","Beyond human chakra lies Senjutsu — drawing natural energy from the surrounding world into the body to enter Sage Mode. The ultimate tier involves Six Paths Chakra and the power of the Tailed Beasts, which grant nearly limitless reality-warping endurance."]',
      'Empathy & Consistent Dedication', 'True strength is not the ability to overpower enemies, but the endurance to understand why they are hurting. Talent is cheap compared to consistent, daily dedication.'
    );
INSERT OR REPLACE INTO anime_aliases (anime_id, alias) VALUES ('naruto-shippuden', 'naruto');
INSERT OR REPLACE INTO anime_aliases (anime_id, alias) VALUES ('naruto-shippuden', 'naruto-shippuden');
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('naruto-shippuden', 'Action');
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('naruto-shippuden', 'Adventure');
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('naruto-shippuden', 'Martial Arts');
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('naruto-shippuden', 'Fantasy');
INSERT OR REPLACE INTO anime_vibes (anime_id, vibe_id) VALUES ('naruto-shippuden', 'like-naruto');
INSERT OR REPLACE INTO anime_vibes (anime_id, vibe_id) VALUES ('naruto-shippuden', 'op-mc');
INSERT OR REPLACE INTO anime_vibes (anime_id, vibe_id) VALUES ('naruto-shippuden', 'beginners');
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('naruto-shippuden', '1–56', 'Canon', 'Kazekage Rescue & Tenchi Bridge Arcs', 1);
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('naruto-shippuden', '57–71', 'Filler', 'Twelve Guardian Ninja Arc (Skip)', 2);
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('naruto-shippuden', '72–90', 'Canon', 'Hidan and Kakuzu Arc', 3);
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('naruto-shippuden', '91–112', 'Filler', 'Three-Tails Appearance Arc (Skip)', 4);
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('naruto-shippuden', '113–143', 'Canon', 'Itachi Pursuit & Master''s Prophecy', 5);
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('naruto-shippuden', '144–151', 'Filler', 'Six-Tails Unleashed Arc (Skip)', 6);
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('naruto-shippuden', '152–175', 'Canon', 'Pain''s Assault Arc', 7);
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('naruto-shippuden', '176–196', 'Filler', 'Past Arc: The Locus of Konoha (Skip)', 8);
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('naruto-shippuden', '197–222', 'Canon', 'Five Kage Summit Arc', 9);
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('naruto-shippuden', '223–242', 'Filler', 'Paradise Life on a Boat (Skip)', 10);
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('naruto-shippuden', '243–256', 'Canon', 'Fourth Shinobi World War: Countdown', 11);
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('naruto-shippuden', '257–260', 'Mixed', 'Flashback Recap', 12);
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('naruto-shippuden', '261–270', 'Canon', 'War: Confrontation', 13);
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('naruto-shippuden', '271', 'Filler', 'Road to Sakura (Skip)', 14);
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('naruto-shippuden', '272–289', 'Canon', 'War: Climax Battalions', 15);
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('naruto-shippuden', '290–295', 'Filler', 'Power Arc (High Animation, but non-canon)', 16);
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('naruto-shippuden', '296–346', 'Canon', 'Reanimated Shinobi & Ten-Tails Revival', 17);
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('naruto-shippuden', '347–361', 'Mixed', 'Kakashi ANBU Flashback (Recommended)', 18);
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('naruto-shippuden', '362–375', 'Canon', 'Return of the God of Shinobi', 19);
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('naruto-shippuden', '376–377', 'Filler', 'Mecha-Naruto Special (Skip)', 20);
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('naruto-shippuden', '378–387', 'Canon', 'Infinite Tsukuyomi Countdown', 21);
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('naruto-shippuden', '388–393', 'Mixed', 'War Flashbacks', 22);
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('naruto-shippuden', '394–413', 'Filler', 'In Naruto’s Footsteps: The Friends’ Paths (Skip)', 23);
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('naruto-shippuden', '414–426', 'Canon', 'Eight Inner Gates & Sage of Six Paths', 24);
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('naruto-shippuden', '427–450', 'Filler', 'Jiraiya Ninja Scrolls & Dream Worlds (Skip)', 25);
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('naruto-shippuden', '451–458', 'Mixed', 'Itachi Shinden: Light and Darkness (Must Watch)', 26);
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('naruto-shippuden', '459–479', 'Canon', 'Kaguya Otsutsuki & Naruto vs. Sasuke Finale', 27);
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('naruto-shippuden', '480–483', 'Filler', 'Childhood Vignettes (Skip)', 28);
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('naruto-shippuden', '484–500', 'Canon', 'Sasuke Shinden, Shikamaru Hiden & Wedding Arc', 29);
INSERT INTO anime_characters (anime_id, rank, name, category, role, commentary) VALUES ('naruto-shippuden', 1, 'Itachi Uchiha', 'Best Written', 'Rogue Shinobi • Akatsuki', 'A tragic martyr whose selfless sacrifice redefines the moral complexity of the entire shinobi system.');
INSERT INTO anime_characters (anime_id, rank, name, category, role, commentary) VALUES ('naruto-shippuden', 2, 'Kakashi Hatake', 'Fan Favorite', 'Leader of Team 7 • Sixth Hokage', 'The emotional anchor of the series, carrying unimaginable loss while remaining a steadfast mentor.');
INSERT INTO anime_characters (anime_id, rank, name, category, role, commentary) VALUES ('naruto-shippuden', 3, 'Pain (Nagato)', 'Best Antagonist', 'Leader of Akatsuki • Six Paths of Pain', 'Delivered the most gripping philosophical confrontation in battle shonen history during the village assault.');
INSERT INTO anime_characters (anime_id, rank, name, category, role, commentary) VALUES ('naruto-shippuden', 4, 'Madara Uchiha', 'Strongest', 'Legendary Clan Leader', 'The gold standard of sheer screen presence and aura; a villain who legitimately lived up to a decade of hype.');
INSERT INTO anime_characters (anime_id, rank, name, category, role, commentary) VALUES ('naruto-shippuden', 5, 'Might Guy', 'Most Underrated', 'Taijutsu Master • Hidden Leaf Jonin', 'Proved that relentless human willpower and physical mastery can stand toe-to-toe with literal gods.');
INSERT OR REPLACE INTO franchises (id, name, description) VALUES ('frieren', 'Frieren: Beyond Journey''s End', NULL);
INSERT INTO franchise_watch_order (franchise_id, step_order, title, type, episodes, anime_id, note) VALUES ('frieren', 1, 'Frieren: Beyond Journey''s End (Season 1)', 'TV Series', '28 Episodes', 'frieren', 'Complete Season 1 covering chapters 1 to 60.');
INSERT OR REPLACE INTO anime (
      id, slug, title, original_title, year, episodes, status,
      personal_rating, poster, backdrop, added_date, last_updated,
      honesty_status, filler_percentage, trending, synopsis,
      franchise_id, franchise_step_order,
      review_heading, review_paragraphs,
      source_title, source_original_title, source_author, source_type,
      source_volumes, source_publication_status, source_adaptation_status,
      source_coverage, source_notes,
      power_system_name, power_system_paragraphs,
      lesson_heading, lesson_takeaway
    ) VALUES (
      'frieren', 'frieren-beyond-journeys-end', 'Frieren: Beyond Journey''s End', '葬送のフリーレン (Sousou no Frieren)', 2023, 28, 'Finished Airing',
      9.8, 'https://image.tmdb.org/t/p/w780/dqZENchTd7lp5zht7BdlqM7RBhD.jpg', 'https://image.tmdb.org/t/p/w1280/5MAq48e77aP78s2C3sZl8Xm3J8d.jpg', 'Jan 15, 2024', 'Oct 20, 2024',
      'watched', 0, 1, 'An immortal elf mage and her human companions defeat the Demon King. But after 50 years pass and her former friends begin to pass away, she embarks on a quiet journey to understand the brevity of human life.',
      'frieren', 1,
      'The Rare Anime That Transcends Its Medium', '["Frieren is easily one of the greatest anime I have ever seen. What makes it so special isn’t just the jaw-dropping animation by Madhouse or Evan Call’s majestic orchestral score — it is the quiet, patient maturity in how it approaches grief, memory, and ordinary everyday moments.","It takes a few episodes to settle into its relaxed rhythm, so if you go in expecting non-stop shonen tournament battles, the deliberate pacing might catch you off guard at first. But once the world opens up, every single interaction carries genuine weight. The magic exam arc in the second half manages to be tactically exhilarating while preserving the introspective soul of the story."]',
      'Frieren: Beyond Journey''s End', '葬送のフリーレン', 'Kanehito Yamada (Story), Tsukasa Abe (Art)', 'Manga',
      '13+ Volumes (Ongoing)', 'Ongoing', 'Ongoing Adaptation',
      'Season 1 adapts Chapters 1 through 60 (up to the conclusion of the First-Class Mage Exam).', 'To continue where the anime left off, start reading at Chapter 61 (Volume 7).',
      'Mana Visualization & Classical Spellcraft', '["Magic in Frieren operates on visualization: a mage cannot manifest a spell unless they can clearly and concretely picture it in their mind. What cannot be visualized is strictly impossible.","Mana control is vital. Skilled mages suppress their leaking mana to fool demon predators into underestimating their lethal range. Combat spells are fast, direct, and lethal, where a single second of distraction results in defeat.","Folk magic (cleaning clothes, turning sweet grapes sour) exists alongside combat spells, representing the everyday beauty of living in a peaceful world."]',
      'The Precious Value of Ordinary Time', 'We live as if we have an infinite supply of tomorrows. Kindness, shared memories, and small everyday moments are the only things that truly survive us.'
    );
INSERT OR REPLACE INTO anime_aliases (anime_id, alias) VALUES ('frieren', 'frieren');
INSERT OR REPLACE INTO anime_aliases (anime_id, alias) VALUES ('frieren', 'frieren-beyond-journeys-end');
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('frieren', 'Fantasy');
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('frieren', 'Adventure');
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('frieren', 'Drama');
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('frieren', 'Slice of Life');
INSERT OR REPLACE INTO anime_vibes (anime_id, vibe_id) VALUES ('frieren', 'zero-filler');
INSERT OR REPLACE INTO anime_vibes (anime_id, vibe_id) VALUES ('frieren', 'hidden-gems');
INSERT OR REPLACE INTO anime_vibes (anime_id, vibe_id) VALUES ('frieren', 'beginners');
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('frieren', '1–28', 'Canon', 'Prologue through First-Class Mage Exam Arc', 1);
INSERT INTO anime_characters (anime_id, rank, name, category, role, commentary) VALUES ('frieren', 1, 'Frieren', 'Best Written', 'Mage • The Slayer', 'A thousand-year-old elf whose quiet growth and sudden bursts of tactical genius redefine fantasy protagonists.');
INSERT INTO anime_characters (anime_id, rank, name, category, role, commentary) VALUES ('frieren', 2, 'Himmel the Hero', 'Fan Favorite', 'Leader of the Hero Party', 'A hero whose vanity is overshadowed only by his profound kindness and enduring influence on everyone he met.');
INSERT INTO anime_characters (anime_id, rank, name, category, role, commentary) VALUES ('frieren', 3, 'Fern', 'Strongest Prodigy', 'Ordinary Offensive Mage', 'Master of basic speed casting, proving that perfect fundamentals beat flashy magic every time.');
INSERT INTO anime_characters (anime_id, rank, name, category, role, commentary) VALUES ('frieren', 4, 'Stark', 'Most Underrated', 'Warrior • Vanguard', 'Terrified before every fight, yet stands firm when it matters most.');
INSERT OR REPLACE INTO franchises (id, name, description) VALUES ('odd-taxi', 'Odd Taxi', NULL);
INSERT INTO franchise_watch_order (franchise_id, step_order, title, type, episodes, anime_id, note) VALUES ('odd-taxi', 1, 'Odd Taxi (TV Series)', 'TV Series', '13 Episodes', 'odd-taxi', 'The complete airtight mystery series.');
INSERT INTO franchise_watch_order (franchise_id, step_order, title, type, episodes, anime_id, note) VALUES ('odd-taxi', 2, 'Odd Taxi: In the Woods', 'Movie', '128 mins', NULL, 'Recap film with a newly animated epilogue scene.');
INSERT OR REPLACE INTO anime (
      id, slug, title, original_title, year, episodes, status,
      personal_rating, poster, backdrop, added_date, last_updated,
      honesty_status, filler_percentage, trending, synopsis,
      franchise_id, franchise_step_order,
      review_heading, review_paragraphs,
      source_title, source_original_title, source_author, source_type,
      source_volumes, source_publication_status, source_adaptation_status,
      source_coverage, source_notes,
      power_system_name, power_system_paragraphs,
      lesson_heading, lesson_takeaway
    ) VALUES (
      'odd-taxi', 'odd-taxi', 'Odd Taxi', 'オッドタクシー', 2021, 13, 'Finished Airing',
      NULL, 'https://image.tmdb.org/t/p/w780/nQhH6eUaT1e1L0aL0s4y7w6v8Z5.jpg', 'https://image.tmdb.org/t/p/w1280/4qW8M2vT0yQ1wP3rY7uK9zO2wN4.jpg', 'Feb 12, 2024', 'Aug 14, 2024',
      'watched', 0, 0, 'An eccentric walrus taxi driver navigates Tokyo nights, carrying passengers whose seemingly unrelated conversations slowly connect to a missing high school girl.',
      'odd-taxi', 1,
      NULL, NULL,
      NULL, NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL
    );
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('odd-taxi', 'Mystery');
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('odd-taxi', 'Psychological');
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('odd-taxi', 'Drama');
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('odd-taxi', 'Thriller');
INSERT OR REPLACE INTO anime_vibes (anime_id, vibe_id) VALUES ('odd-taxi', 'hidden-gems');
INSERT OR REPLACE INTO anime_vibes (anime_id, vibe_id) VALUES ('odd-taxi', 'zero-filler');
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('odd-taxi', '1–13', 'Canon', 'The Full Interconnected Tokyo Case', 1);
INSERT INTO anime_characters (anime_id, rank, name, category, role, commentary) VALUES ('odd-taxi', 1, 'Hiroshi Odokawa', 'Best Written', 'Walrus Taxi Driver', 'A cynical, deadpan driver with exceptional observational memory and a hidden past.');
INSERT INTO anime_characters (anime_id, rank, name, category, role, commentary) VALUES ('odd-taxi', 2, 'Dobu', 'Fan Favorite', 'Yakuza Enforcer', 'Intelligent, street-smart mobster who trades razor-sharp dialogue with Odokawa.');
INSERT INTO anime_characters (anime_id, rank, name, category, role, commentary) VALUES ('odd-taxi', 3, 'Yano', 'Most Underrated', 'Rap-Speaking Gangster', 'Rhymes every line with rhythmic menace and erratic charisma.');
INSERT OR REPLACE INTO franchises (id, name, description) VALUES ('jujutsu-kaisen', 'Jujutsu Kaisen', NULL);
INSERT INTO franchise_watch_order (franchise_id, step_order, title, type, episodes, anime_id, note) VALUES ('jujutsu-kaisen', 1, 'Jujutsu Kaisen Season 1', 'TV Series', '24 Episodes', NULL, 'Introduces Yuji Itadori and Jujutsu High fundamentals.');
INSERT INTO franchise_watch_order (franchise_id, step_order, title, type, episodes, anime_id, note) VALUES ('jujutsu-kaisen', 2, 'Jujutsu Kaisen 0 (Movie)', 'Movie', '105 mins', NULL, 'MANDATORY PREQUEL. Sets up Suguru Geto and Yuta Okkotsu before Season 2.');
INSERT INTO franchise_watch_order (franchise_id, step_order, title, type, episodes, anime_id, note) VALUES ('jujutsu-kaisen', 3, 'Jujutsu Kaisen Season 2 (Hidden Inventory & Shibuya Incident)', 'TV Series', '23 Episodes', 'jujutsu-kaisen', 'Gojo’s past followed by the catastrophic Shibuya Incident.');
INSERT OR REPLACE INTO anime (
      id, slug, title, original_title, year, episodes, status,
      personal_rating, poster, backdrop, added_date, last_updated,
      honesty_status, filler_percentage, trending, synopsis,
      franchise_id, franchise_step_order,
      review_heading, review_paragraphs,
      source_title, source_original_title, source_author, source_type,
      source_volumes, source_publication_status, source_adaptation_status,
      source_coverage, source_notes,
      power_system_name, power_system_paragraphs,
      lesson_heading, lesson_takeaway
    ) VALUES (
      'jujutsu-kaisen', 'jujutsu-kaisen', 'Jujutsu Kaisen', '呪術廻戦', 2020, 47, 'Ongoing',
      9.2, 'https://image.tmdb.org/t/p/w780/hFWP5HkbVEe40hrXgtCe5xUCvM7.jpg', 'https://image.tmdb.org/t/p/w1280/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg', 'Jan 18, 2024', 'Nov 01, 2024',
      'watched', 0, 1, 'A high schooler with astonishing physical prowess swallows a cursed talisman to save a friend, becoming host to the Legendary King of Curses Ryomen Sukuna.',
      'jujutsu-kaisen', 3,
      'Pure Kinetic Adrenaline with Unforgiving Stakes', '["MAPPA went completely feral on the animation in Season 2. The Shibuya Incident is a non-stop gauntlet where every episode feels like a season finale, and the series is completely unafraid to kill off beloved characters or put them through absolute psychological misery.","My only real critique is that the pacing is so relentless that there is almost zero downtime for quiet character banter once the action kicks off. But as far as raw sakuga combat, inventive power systems, and high emotional stakes go, it is modern battle shonen operating at the absolute highest level."]',
      'Jujutsu Kaisen', '呪術廻戦', 'Gege Akutami', 'Manga',
      '28+ Volumes (Completed in Manga)', 'Completed (2018 – 2024)', 'Ongoing Adaptation',
      'Season 2 finishes at Chapter 137. The manga concludes at Chapter 271.', 'To continue after Shibuya, start reading at Chapter 138 (Culling Game Arc).',
      'Cursed Energy & Domain Expansion', '["Cursed Energy leaks from the negative emotions of humans. Sorcerers channel this raw energy into refined Cursed Techniques imprinted into their bodies from birth.","The pinnacle of jujutsu is Domain Expansion: creating a separate metaphysical space imbued with the user’s innate technique where all attacks are guaranteed to hit.","Binding Vows allow sorcerers to artificially create self-imposed restrictions (such as explaining their technique to the opponent) in exchange for exponential increases in output."]',
      NULL, NULL
    );
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('jujutsu-kaisen', 'Action');
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('jujutsu-kaisen', 'Dark Fantasy');
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('jujutsu-kaisen', 'Supernatural');
INSERT OR REPLACE INTO anime_vibes (anime_id, vibe_id) VALUES ('jujutsu-kaisen', 'op-mc');
INSERT OR REPLACE INTO anime_vibes (anime_id, vibe_id) VALUES ('jujutsu-kaisen', 'like-naruto');
INSERT OR REPLACE INTO anime_vibes (anime_id, vibe_id) VALUES ('jujutsu-kaisen', 'zero-filler');
INSERT OR REPLACE INTO anime_vibes (anime_id, vibe_id) VALUES ('jujutsu-kaisen', 'beginners');
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('jujutsu-kaisen', '1–24', 'Canon', 'Fearsome Womb through Death Painting Arc', 1);
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('jujutsu-kaisen', '25–29', 'Canon', 'Hidden Inventory / Premature Death Arc', 2);
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('jujutsu-kaisen', '30–47', 'Canon', 'Shibuya Incident Arc', 3);
INSERT INTO anime_characters (anime_id, rank, name, category, role, commentary) VALUES ('jujutsu-kaisen', 1, 'Satoru Gojo', 'Strongest', 'Special Grade Sorcerer', 'The unrivaled pinnacle of the modern jujutsu world whose birth shifted the balance of existence.');
INSERT INTO anime_characters (anime_id, rank, name, category, role, commentary) VALUES ('jujutsu-kaisen', 2, 'Toji Fushiguro', 'Fan Favorite', 'The Sorcerer Killer', 'Zero cursed energy, pure physical savagery and tactical brilliance.');
INSERT INTO anime_characters (anime_id, rank, name, category, role, commentary) VALUES ('jujutsu-kaisen', 3, 'Ryomen Sukuna', 'Best Antagonist', 'King of Curses', 'An unrelenting force of calamity who acts entirely on his own chaotic whims.');
INSERT OR REPLACE INTO franchises (id, name, description) VALUES ('vinland-saga', 'Vinland Saga', NULL);
INSERT INTO franchise_watch_order (franchise_id, step_order, title, type, episodes, anime_id, note) VALUES ('vinland-saga', 1, 'Vinland Saga Season 1 (WIT Studio)', 'TV Series', '24 Episodes', NULL, 'The War/Prologue Arc focusing on Askeladd and young Thorfinn.');
INSERT INTO franchise_watch_order (franchise_id, step_order, title, type, episodes, anime_id, note) VALUES ('vinland-saga', 2, 'Vinland Saga Season 2 (MAPPA)', 'TV Series', '24 Episodes', 'vinland-saga', 'The Slave / Ketil’s Farm Arc, a deep philosophical turning point.');
INSERT OR REPLACE INTO anime (
      id, slug, title, original_title, year, episodes, status,
      personal_rating, poster, backdrop, added_date, last_updated,
      honesty_status, filler_percentage, trending, synopsis,
      franchise_id, franchise_step_order,
      review_heading, review_paragraphs,
      source_title, source_original_title, source_author, source_type,
      source_volumes, source_publication_status, source_adaptation_status,
      source_coverage, source_notes,
      power_system_name, power_system_paragraphs,
      lesson_heading, lesson_takeaway
    ) VALUES (
      'vinland-saga', 'vinland-saga', 'Vinland Saga', 'ヴィンランド・サガ', 2019, 48, 'Finished Airing',
      9.5, 'https://image.tmdb.org/t/p/w780/4N3kX2V6wD0sI7QvR0vGj4lM9W2.jpg', 'https://image.tmdb.org/t/p/w1280/5MAq48e77aP78s2C3sZl8Xm3J8d.jpg', 'Jan 22, 2024', 'Sep 30, 2024',
      'watched', 2, 1, 'Raised by the Vikings who murdered his father, young Thorfinn dedicates his life to dueling their leader Askeladd in an insatiable quest for revenge.',
      'vinland-saga', 2,
      NULL, NULL,
      'Vinland Saga', 'ヴィンランド・サガ', 'Makoto Yukimura', 'Manga',
      '28+ Volumes (Ongoing / Near Climax)', 'Ongoing', 'Ongoing Adaptation',
      'Anime adapts Chapters 1 through 100 (Volumes 1–14).', 'To continue reading after Season 2, start at Chapter 101 (Eastern Expedition Arc).',
      NULL, NULL,
      'True Strength & Empathy', 'Revenge leaves you empty. True strength isn’t holding a sharper blade — it is having the courage to refuse violence and choose empathy even when striking is easiest.'
    );
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('vinland-saga', 'Action');
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('vinland-saga', 'Historical');
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('vinland-saga', 'Drama');
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('vinland-saga', 'Psychological');
INSERT OR REPLACE INTO anime_vibes (anime_id, vibe_id) VALUES ('vinland-saga', 'zero-filler');
INSERT OR REPLACE INTO anime_vibes (anime_id, vibe_id) VALUES ('vinland-saga', 'hidden-gems');
INSERT OR REPLACE INTO anime_vibes (anime_id, vibe_id) VALUES ('vinland-saga', 'beginners');
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('vinland-saga', '1–24', 'Canon', 'Prologue / War Arc', 1);
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('vinland-saga', '25–48', 'Canon', 'Slave / Farmland Arc', 2);
INSERT INTO anime_characters (anime_id, rank, name, category, role, commentary) VALUES ('vinland-saga', 1, 'Askeladd', 'Best Written', 'Viking Band Commander', 'One of the greatest anti-heroes in modern media; brilliant, ruthless, yet secretly harboring profound idealism.');
INSERT INTO anime_characters (anime_id, rank, name, category, role, commentary) VALUES ('vinland-saga', 2, 'Thorfinn Karlsefni', 'Most Evolved', 'Warrior turned Pacifist', 'Undergoes one of the most agonizing and earned redemptive transformations ever animated.');
INSERT INTO anime_characters (anime_id, rank, name, category, role, commentary) VALUES ('vinland-saga', 3, 'Thors the Troll', 'Strongest Moral Core', 'Legendary Jomsviking', 'A true warrior needs no sword. His creed echoes across the entire narrative.');
INSERT OR REPLACE INTO franchises (id, name, description) VALUES ('solo-leveling', 'Solo Leveling', NULL);
INSERT INTO franchise_watch_order (franchise_id, step_order, title, type, episodes, anime_id, note) VALUES ('solo-leveling', 1, 'Solo Leveling Season 1', 'TV Series', '12 Episodes', NULL, 'Covers D-Rank dungeon to the Job Change quest.');
INSERT INTO franchise_watch_order (franchise_id, step_order, title, type, episodes, anime_id, note) VALUES ('solo-leveling', 2, 'Solo Leveling: ReAwakening', 'Movie / Special', '115 mins', NULL, 'Recap of S1 + early preview of S2 episodes.');
INSERT INTO franchise_watch_order (franchise_id, step_order, title, type, episodes, anime_id, note) VALUES ('solo-leveling', 3, 'Solo Leveling Season 2: Arise from the Shadow', 'TV Series', '13 Episodes', 'solo-leveling', 'Red Gate and Demon Castle arcs.');
INSERT OR REPLACE INTO anime (
      id, slug, title, original_title, year, episodes, status,
      personal_rating, poster, backdrop, added_date, last_updated,
      honesty_status, filler_percentage, trending, synopsis,
      franchise_id, franchise_step_order,
      review_heading, review_paragraphs,
      source_title, source_original_title, source_author, source_type,
      source_volumes, source_publication_status, source_adaptation_status,
      source_coverage, source_notes,
      power_system_name, power_system_paragraphs,
      lesson_heading, lesson_takeaway
    ) VALUES (
      'solo-leveling', 'solo-leveling', 'Solo Leveling', '나 혼자만 레벨업 (Ore dake Level Up na Ken)', 2024, 25, 'Ongoing',
      8.8, 'https://image.tmdb.org/t/p/w780/geCRueV3ElhRTr0xtJuPxJ8HGQH.jpg', 'https://image.tmdb.org/t/p/w1280/2rmK7mnchsl935x82Rp8ea7LZkd.jpg', 'Jan 25, 2024', 'Nov 04, 2024',
      'watched', 0, 1, 'Known as the weakest hunter of all mankind, Sung Jinwoo is trapped in a deadly double dungeon. Surviving against all odds, a mysterious quest log grants him the ability to level up infinitely.',
      'solo-leveling', 3,
      'The Gold Standard of Power Fantasy Dopamine', '["Solo Leveling does not pretend to be a deep philosophical meditation — it is pure, unadulterated power fantasy progression, and it executes that formula better than almost anything else. Sung Jinwoo’s rise from bottom-tier fodder to commanding legions of shadow soldiers is accompanied by Hiroyuki Sawano’s pulse-pounding soundtrack.","The supporting cast definitely takes a back seat as Jinwoo scales up, but if you want crisp fight animation, crunchy impact sounds, and pure hype payoffs, this delivers in spades."]',
      'Solo Leveling (Only I Level Up)', '나 혼자만 level up', 'Chugong (Novel), DUBU/REDICE (Webtoon Art)', 'Webtoon / Manhwa',
      '179 Chapters (Completed)', 'Completed (2018 – 2021)', 'Ongoing Adaptation',
      'Season 1 covers webtoon Chapters 1 to 45.', 'Webtoon is fully completed and available in full-color format.',
      'Hunter Awakening & The System', '["In the world of Solo Leveling, humans undergo an \"Awakening\" that grants them fixed magical ranks from E to S. Ranks are strictly permanent and cannot be increased through training.","Sung Jinwoo is the sole exception: the \"System\" turns his reality into an RPG interface with daily quests, stat points, inventory storage, and skill trees.","His primary class ability, Shadow Extraction, extracts souls from fallen enemies to forge an immortal army of loyal shadows."]',
      NULL, NULL
    );
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('solo-leveling', 'Action');
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('solo-leveling', 'Fantasy');
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('solo-leveling', 'Supernatural');
INSERT OR REPLACE INTO anime_vibes (anime_id, vibe_id) VALUES ('solo-leveling', 'op-mc');
INSERT OR REPLACE INTO anime_vibes (anime_id, vibe_id) VALUES ('solo-leveling', 'beginners');
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('solo-leveling', '1–7', 'Canon', 'D-Rank Dungeon & Kasaka Arc', 1);
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('solo-leveling', '7.5', 'Filler', 'Mid-Season Recap (Skip)', 2);
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('solo-leveling', '8–12', 'Canon', 'Job Change & Necromancer Arc', 3);
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('solo-leveling', '13–25', 'Canon', 'Red Gate & Jeju Island Build-up', 4);
INSERT INTO anime_characters (anime_id, rank, name, category, role, commentary) VALUES ('solo-leveling', 1, 'Sung Jinwoo', 'Strongest', 'Shadow Monarch', 'Starts as an E-rank laughingstock and rises to command legions of undead shadows.');
INSERT INTO anime_characters (anime_id, rank, name, category, role, commentary) VALUES ('solo-leveling', 2, 'Igris', 'Fan Favorite', 'Blood-Red Commander', 'The loyal knight shadow whose chivalrous demeanor steals every fight scene.');
INSERT INTO anime_characters (anime_id, rank, name, category, role, commentary) VALUES ('solo-leveling', 3, 'Cha Hae-In', 'Best Written', 'S-Rank Hunter', 'One of the few top-tier hunters with genuine tactical instinct.');
INSERT OR REPLACE INTO franchises (id, name, description) VALUES ('dangers-in-my-heart', 'The Dangers in My Heart', NULL);
INSERT INTO franchise_watch_order (franchise_id, step_order, title, type, episodes, anime_id, note) VALUES ('dangers-in-my-heart', 1, 'The Dangers in My Heart Season 1', 'TV Series', '12 Episodes', NULL, 'Covers the early library encounters and growing mutual trust.');
INSERT INTO franchise_watch_order (franchise_id, step_order, title, type, episodes, anime_id, note) VALUES ('dangers-in-my-heart', 2, 'The Dangers in My Heart Season 2', 'TV Series', '13 Episodes', 'dangers-in-my-heart', 'School trip and historic confession payoffs.');
INSERT OR REPLACE INTO anime (
      id, slug, title, original_title, year, episodes, status,
      personal_rating, poster, backdrop, added_date, last_updated,
      honesty_status, filler_percentage, trending, synopsis,
      franchise_id, franchise_step_order,
      review_heading, review_paragraphs,
      source_title, source_original_title, source_author, source_type,
      source_volumes, source_publication_status, source_adaptation_status,
      source_coverage, source_notes,
      power_system_name, power_system_paragraphs,
      lesson_heading, lesson_takeaway
    ) VALUES (
      'dangers-in-my-heart', 'the-dangers-in-my-heart', 'The Dangers in My Heart', '僕の心のヤバイやつ (Boku no Kokoro no Yabai Yatsu)', 2023, 25, 'Finished Airing',
      9.1, 'https://image.tmdb.org/t/p/w780/b5rX1b9dC1E8OQ102F3J2lT2YtN.jpg', 'https://image.tmdb.org/t/p/w1280/pBqg8G1f0M3Vw6c3qJ1iK7y5W4D.jpg', 'Feb 01, 2024', 'Oct 15, 2024',
      'watched', 0, 1, 'Kyotaro Ichikawa, an antisocial middle schooler with bizarre murder fantasies, discovers that the popular school idol Anna Yamada is surprisingly quirky, hungry, and oblivious.',
      'dangers-in-my-heart', 2,
      NULL, NULL,
      'The Dangers in My Heart', '僕の心のヤバイやつ', 'Norio Sakurai', 'Manga',
      '10+ Volumes (Ongoing)', 'Ongoing', 'Ongoing Adaptation',
      'Seasons 1 & 2 adapt Chapters 1 through 113 (Volume 8).', 'Read from Chapter 114 to continue the story in high school.',
      NULL, NULL,
      'Vulnerability Over Defensive Armor', 'Vulnerability is not weakness. Real connection only begins when we drop the defensive armor and risk looking foolish in front of someone we care about.'
    );
INSERT OR REPLACE INTO anime_aliases (anime_id, alias) VALUES ('dangers-in-my-heart', 'dangers-in-my-heart');
INSERT OR REPLACE INTO anime_aliases (anime_id, alias) VALUES ('dangers-in-my-heart', 'the-dangers-in-my-heart');
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('dangers-in-my-heart', 'Romance');
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('dangers-in-my-heart', 'Comedy');
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('dangers-in-my-heart', 'Slice of Life');
INSERT OR REPLACE INTO anime_vibes (anime_id, vibe_id) VALUES ('dangers-in-my-heart', 'slow-burn-romance');
INSERT OR REPLACE INTO anime_vibes (anime_id, vibe_id) VALUES ('dangers-in-my-heart', 'hidden-gems');
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('dangers-in-my-heart', '1–25', 'Canon', 'Manga Volumes 1 through 8', 1);
INSERT INTO anime_characters (anime_id, rank, name, category, role, commentary) VALUES ('dangers-in-my-heart', 1, 'Anna Yamada', 'Fan Favorite', 'Junior Model & Class Idol', 'Endearingly dorky, expressive, and direct in her affections.');
INSERT INTO anime_characters (anime_id, rank, name, category, role, commentary) VALUES ('dangers-in-my-heart', 2, 'Kyotaro Ichikawa', 'Best Written', 'Middle School Protagonist', 'Transitions from insecure teenage angst to a caring, self-aware partner.');
INSERT OR REPLACE INTO franchises (id, name, description) VALUES ('apothecary-diaries', 'The Apothecary Diaries', NULL);
INSERT INTO franchise_watch_order (franchise_id, step_order, title, type, episodes, anime_id, note) VALUES ('apothecary-diaries', 1, 'The Apothecary Diaries Season 1', 'TV Series', '24 Episodes', 'apothecary-diaries', 'Covers Light Novel Volumes 1 and 2.');
INSERT OR REPLACE INTO anime (
      id, slug, title, original_title, year, episodes, status,
      personal_rating, poster, backdrop, added_date, last_updated,
      honesty_status, filler_percentage, trending, synopsis,
      franchise_id, franchise_step_order,
      review_heading, review_paragraphs,
      source_title, source_original_title, source_author, source_type,
      source_volumes, source_publication_status, source_adaptation_status,
      source_coverage, source_notes,
      power_system_name, power_system_paragraphs,
      lesson_heading, lesson_takeaway
    ) VALUES (
      'apothecary-diaries', 'the-apothecary-diaries', 'The Apothecary Diaries', '薬屋のひとりごと (Kusuriya no Hitorigoto)', 2023, 24, 'Ongoing',
      9, 'https://image.tmdb.org/t/p/w780/gL0s3k3zOQ7y9wP4rW6V8Y0Z2N2.jpg', 'https://image.tmdb.org/t/p/w1280/8wW1qP8wW2yT8wM9aY7uO2yM4n8.jpg', 'Feb 15, 2024', 'Nov 03, 2024',
      'watched', 0, 1, 'Kidnapped and sold into the imperial palace, an eccentric apothecary with a taste for poisons solves medical mysteries that threaten royal consorts.',
      'apothecary-diaries', 1,
      'Witty, Beautifully Crafted Palace Intrigue', '["Maomao is instantly one of my favorite female protagonists in recent memory. She is unapologetically cynical, pragmatic, and obsessed with poison and medicinal herbs, which makes watching her untangle imperial palace conspiracies endlessly entertaining.","Some of the court politics and clan rivalries can get a bit dense in the middle episodes, but the gorgeous art direction and the hilarious dynamic between Maomao and Jinshi keep the momentum fresh throughout."]',
      'The Apothecary Diaries', '薬屋のひとりごと', 'Natsu Hyuuga (Novel), Nekokurage (Manga)', 'Light Novel & Manga',
      '15+ Light Novel Volumes', 'Ongoing', 'Ongoing Adaptation',
      'Season 1 covers Light Novel Volumes 1 & 2 (Manga Chapters 1–40).', 'Season 2 begins at Light Novel Volume 3.',
      NULL, NULL,
      NULL, NULL
    );
INSERT OR REPLACE INTO anime_aliases (anime_id, alias) VALUES ('apothecary-diaries', 'apothecary-diaries');
INSERT OR REPLACE INTO anime_aliases (anime_id, alias) VALUES ('apothecary-diaries', 'the-apothecary-diaries');
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('apothecary-diaries', 'Mystery');
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('apothecary-diaries', 'Historical');
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('apothecary-diaries', 'Drama');
INSERT OR REPLACE INTO anime_vibes (anime_id, vibe_id) VALUES ('apothecary-diaries', 'hidden-gems');
INSERT OR REPLACE INTO anime_vibes (anime_id, vibe_id) VALUES ('apothecary-diaries', 'slow-burn-romance');
INSERT OR REPLACE INTO anime_vibes (anime_id, vibe_id) VALUES ('apothecary-diaries', 'zero-filler');
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('apothecary-diaries', '1–24', 'Canon', 'Imperial Rear Palace Mysteries', 1);
INSERT INTO anime_characters (anime_id, rank, name, category, role, commentary) VALUES ('apothecary-diaries', 1, 'Maomao', 'Best Written', 'Palace Poison Tester & Apothecary', 'A pragmatic, brilliant heroine who cares more about rare herbs than royal prestige.');
INSERT INTO anime_characters (anime_id, rank, name, category, role, commentary) VALUES ('apothecary-diaries', 2, 'Jinshi', 'Fan Favorite', 'Palace Eunuch / Imperial Administrator', 'Charming, manipulative, yet perpetually flustered by Maomao’s total indifference to his looks.');
INSERT OR REPLACE INTO franchises (id, name, description) VALUES ('mob-psycho-100', 'Mob Psycho 100', NULL);
INSERT INTO franchise_watch_order (franchise_id, step_order, title, type, episodes, anime_id, note) VALUES ('mob-psycho-100', 1, 'Mob Psycho 100 (Season 1)', 'TV Series', '12 Episodes', NULL, 'Introduces Mob, Reigen, and Claw 7th Division.');
INSERT INTO franchise_watch_order (franchise_id, step_order, title, type, episodes, anime_id, note) VALUES ('mob-psycho-100', 2, 'Mob Psycho 100 II (Season 2)', 'TV Series', '13 Episodes', NULL, 'Mogami Arc and Claw World Domination Arc.');
INSERT INTO franchise_watch_order (franchise_id, step_order, title, type, episodes, anime_id, note) VALUES ('mob-psycho-100', 3, 'Mob Psycho 100 III (Season 3)', 'TV Series', '12 Episodes', 'mob-psycho-100', 'Divine Tree and Confession Arc (Series Finale).');
INSERT OR REPLACE INTO anime (
      id, slug, title, original_title, year, episodes, status,
      personal_rating, poster, backdrop, added_date, last_updated,
      honesty_status, filler_percentage, trending, synopsis,
      franchise_id, franchise_step_order,
      review_heading, review_paragraphs,
      source_title, source_original_title, source_author, source_type,
      source_volumes, source_publication_status, source_adaptation_status,
      source_coverage, source_notes,
      power_system_name, power_system_paragraphs,
      lesson_heading, lesson_takeaway
    ) VALUES (
      'mob-psycho-100', 'mob-psycho-100', 'Mob Psycho 100', 'モブサイコ100', 2016, 37, 'Finished Airing',
      9.7, 'https://image.tmdb.org/t/p/w780/29A2n2M8G6xY5y1Q3rG0sK7w8p9.jpg', 'https://image.tmdb.org/t/p/w1280/3wY8M2V8kQ9y7wW6uY4pZ1yK0m5.jpg', 'Jan 05, 2024', 'Aug 25, 2024',
      'watched', 0, 0, 'An eighth-grader with godlike psychic abilities suppresses his emotions to prevent psychic explosions, seeking only to improve his physical fitness to impress his middle-school crush.',
      'mob-psycho-100', 3,
      'One of the Rare Complete, Flawless Three-Season Runs', '["Mob Psycho 100 has everything: mind-bending sakuga animation from Studio BONES, genuine belly-laugh humor, and arguably the most wholesome emotional core in all of anime. Reigen Arataka could have easily been an annoying gimmick character, but he turns out to be one of the best mentors ever written.","All three seasons tell a complete, tightly paced story with zero wasted episodes, ending on the rare, coveted perfect series finale."]',
      'Mob Psycho 100', 'モブサイコ100', 'ONE', 'Manga',
      '16 Volumes / 101 Chapters', 'Completed (2012 – 2017)', 'Fully Adapted',
      'The anime adapts the entire manga from Chapter 1 to 101 with complete closure.', 'No manga reading required after finishing Season 3.',
      'Esper Telekinesis & Emotional Threshold (100%)', '["Psychic power in Mob Psycho 100 is fueled by suppressed human emotions: Anger, Sadness, Gratitude, and Courage.","When Mob reaches 100% emotional intensity, his psychic seal bursts, unleashing city-level telekinetic storms. If knocked unconscious, his subconscious \"???%\" mode emerges with cataclysmic scale."]',
      'Humility & Working on What’s Difficult', 'Having a special talent doesn’t make you better than anyone else. True self-esteem comes from working hard on the things that are genuinely difficult for you.'
    );
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('mob-psycho-100', 'Action');
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('mob-psycho-100', 'Comedy');
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('mob-psycho-100', 'Supernatural');
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('mob-psycho-100', 'Slice of Life');
INSERT OR REPLACE INTO anime_vibes (anime_id, vibe_id) VALUES ('mob-psycho-100', 'op-mc');
INSERT OR REPLACE INTO anime_vibes (anime_id, vibe_id) VALUES ('mob-psycho-100', 'zero-filler');
INSERT OR REPLACE INTO anime_vibes (anime_id, vibe_id) VALUES ('mob-psycho-100', 'beginners');
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('mob-psycho-100', '1–37', 'Canon', 'Full Complete Manga Adaptation', 1);
INSERT INTO anime_characters (anime_id, rank, name, category, role, commentary) VALUES ('mob-psycho-100', 1, 'Reigen Arataka', 'Best Written', 'Spirits and Such Consultation', 'A con-man with zero spiritual power who is nonetheless the greatest moral guide a child could have.');
INSERT INTO anime_characters (anime_id, rank, name, category, role, commentary) VALUES ('mob-psycho-100', 2, 'Shigeo Kageyama (Mob)', 'Most Wholesome', 'Psychic Middle Schooler', 'Possesses godlike power, yet values kindness, running club sweat, and friendship above all else.');
INSERT OR REPLACE INTO franchises (id, name, description) VALUES ('bleach', 'Bleach', NULL);
INSERT INTO franchise_watch_order (franchise_id, step_order, title, type, episodes, anime_id, note) VALUES ('bleach', 1, 'Bleach: Thousand-Year Blood War (Cour 1: The Blood Warfare)', 'TV Series', '13 Episodes', NULL, 'Quincy invasion of Soul Society.');
INSERT INTO franchise_watch_order (franchise_id, step_order, title, type, episodes, anime_id, note) VALUES ('bleach', 2, 'Cour 2: The Separation', 'TV Series', '13 Episodes', NULL, 'Second invasion with expanded anime-original Bankai.');
INSERT INTO franchise_watch_order (franchise_id, step_order, title, type, episodes, anime_id, note) VALUES ('bleach', 3, 'Cour 3: The Conflict', 'TV Series', '13 Episodes', 'bleach-tybw', 'Royal Palace invasion and Squad Zero battle.');
INSERT OR REPLACE INTO anime (
      id, slug, title, original_title, year, episodes, status,
      personal_rating, poster, backdrop, added_date, last_updated,
      honesty_status, filler_percentage, trending, synopsis,
      franchise_id, franchise_step_order,
      review_heading, review_paragraphs,
      source_title, source_original_title, source_author, source_type,
      source_volumes, source_publication_status, source_adaptation_status,
      source_coverage, source_notes,
      power_system_name, power_system_paragraphs,
      lesson_heading, lesson_takeaway
    ) VALUES (
      'bleach-tybw', 'bleach-thousand-year-blood-war', 'Bleach: Thousand-Year Blood War', 'BLEACH 千年血戦篇', 2022, 39, 'Ongoing',
      NULL, 'https://image.tmdb.org/t/p/w780/b5rX1b9dC1E8OQ102F3J2lT2YtN.jpg', 'https://image.tmdb.org/t/p/w1280/vIjyK706i8qfU3556gVvJ8Z8V6X.jpg', 'Jan 28, 2024', 'Nov 02, 2024',
      'watchlist', 0, 1, 'Peace is shattered when an alarm sounds through the Soul Society. The Quincy King Yhwach emerges from the shadows to wage total war against the Soul Reapers.',
      'bleach', 3,
      NULL, NULL,
      'Bleach', 'BLEACH', 'Tite Kubo', 'Manga',
      '74 Volumes / 686 Chapters', 'Completed', 'Ongoing Final Arc Adaptation',
      'Adapts the final manga arc Chapters 480 to 686 across 4 cours.', 'Includes brand new fight choreography not present in the original manga.',
      'Reiryoku, Zanpakuto & Bankai', '["Soul Reapers channel spiritual pressure (Reiatsu) through their Zanpakuto, calling upon Shikai (initial release) and Bankai (ultimate manifestation).","Quincies manipulate reishi in the environment and utilize Vollständig to manifest divine angelic combat forms."]',
      NULL, NULL
    );
INSERT OR REPLACE INTO anime_aliases (anime_id, alias) VALUES ('bleach-tybw', 'bleach-tybw');
INSERT OR REPLACE INTO anime_aliases (anime_id, alias) VALUES ('bleach-tybw', 'bleach');
INSERT OR REPLACE INTO anime_aliases (anime_id, alias) VALUES ('bleach-tybw', 'bleach-thousand-year-blood-war');
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('bleach-tybw', 'Action');
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('bleach-tybw', 'Supernatural');
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('bleach-tybw', 'Adventure');
INSERT OR REPLACE INTO anime_vibes (anime_id, vibe_id) VALUES ('bleach-tybw', 'op-mc');
INSERT OR REPLACE INTO anime_vibes (anime_id, vibe_id) VALUES ('bleach-tybw', 'like-naruto');
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('bleach-tybw', '1–39', 'Canon', 'Manga Chapters 480–686 with expanded scenes', 1);
INSERT INTO anime_characters (anime_id, rank, name, category, role, commentary) VALUES ('bleach-tybw', 1, 'Ichigo Kurosaki', 'Strongest', 'Substitute Soul Reaper', 'Unlocks the true dual-blade manifestation of his Soul Reaper and Quincy ancestry.');
INSERT INTO anime_characters (anime_id, rank, name, category, role, commentary) VALUES ('bleach-tybw', 2, 'Yhwach', 'Best Antagonist', 'Father of the Quincy', 'Wields "The Almighty" to perceive and rewrite future timelines.');
INSERT OR REPLACE INTO franchises (id, name, description) VALUES ('kaiju-no-8', 'Kaiju No. 8', NULL);
INSERT INTO franchise_watch_order (franchise_id, step_order, title, type, episodes, anime_id, note) VALUES ('kaiju-no-8', 1, 'Kaiju No. 8 Season 1', 'TV Series', '12 Episodes', 'kaiju-no-8', 'Covers the Defense Force Exam and Tachikawa Base raid.');
INSERT OR REPLACE INTO anime (
      id, slug, title, original_title, year, episodes, status,
      personal_rating, poster, backdrop, added_date, last_updated,
      honesty_status, filler_percentage, trending, synopsis,
      franchise_id, franchise_step_order,
      review_heading, review_paragraphs,
      source_title, source_original_title, source_author, source_type,
      source_volumes, source_publication_status, source_adaptation_status,
      source_coverage, source_notes,
      power_system_name, power_system_paragraphs,
      lesson_heading, lesson_takeaway
    ) VALUES (
      'kaiju-no-8', 'kaiju-no-8', 'Kaiju No. 8', '怪獣8号 (Kaijuu 8-gou)', 2024, 12, 'Ongoing',
      NULL, 'https://image.tmdb.org/t/p/w780/8wW1qP8wW2yT8wM9aY7uO2yM4n8.jpg', 'https://image.tmdb.org/t/p/w1280/5MAq48e77aP78s2C3sZl8Xm3J8d.jpg', 'Feb 20, 2024', 'Jul 15, 2024',
      'watchlist', 0, 0, 'A 32-year-old kaiju corpse cleaner gets infected by a tiny monster, gaining the ability to transform into the lethal humanoid Kaiju No. 8.',
      'kaiju-no-8', 1,
      NULL, NULL,
      'Kaiju No. 8', '怪獣8号', 'Naoya Matsumoto', 'Manga',
      '13+ Volumes (Ongoing)', 'Ongoing', 'Ongoing Adaptation',
      'Season 1 adapts Chapters 1 through 38.', 'Read from Chapter 39 to continue the story in the manga.',
      NULL, NULL,
      NULL, NULL
    );
INSERT OR REPLACE INTO anime_aliases (anime_id, alias) VALUES ('kaiju-no-8', 'kaiju-no-8');
INSERT OR REPLACE INTO anime_aliases (anime_id, alias) VALUES ('kaiju-no-8', 'kaiju8');
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('kaiju-no-8', 'Action');
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('kaiju-no-8', 'Sci-Fi');
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('kaiju-no-8', 'Military');
INSERT OR REPLACE INTO anime_vibes (anime_id, vibe_id) VALUES ('kaiju-no-8', 'op-mc');
INSERT OR REPLACE INTO anime_vibes (anime_id, vibe_id) VALUES ('kaiju-no-8', 'beginners');
INSERT OR REPLACE INTO anime_vibes (anime_id, vibe_id) VALUES ('kaiju-no-8', 'like-naruto');
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('kaiju-no-8', '1–12', 'Canon', 'Manga Volumes 1 through 5', 1);
INSERT INTO anime_characters (anime_id, rank, name, category, role, commentary) VALUES ('kaiju-no-8', 1, 'Kafka Hibino / Kaiju No. 8', 'Best Written', 'Defense Force Cadet', 'A refreshing 32-year-old working-class protagonist refusing to give up on his childhood promise.');
INSERT INTO anime_characters (anime_id, rank, name, category, role, commentary) VALUES ('kaiju-no-8', 2, 'Mina Ashiro', 'Strongest', 'Captain of the Third Division', 'Heavy artillery marksman capable of single-handedly obliterating giant Honju kaiju.');
INSERT OR REPLACE INTO franchises (id, name, description) VALUES ('kaguya-sama', 'Kaguya-sama: Love Is War', NULL);
INSERT INTO franchise_watch_order (franchise_id, step_order, title, type, episodes, anime_id, note) VALUES ('kaguya-sama', 1, 'Kaguya-sama: Love Is War (Season 1)', 'TV Series', '12 Episodes', NULL, 'Introduces the student council mind games and fireworks finale.');
INSERT INTO franchise_watch_order (franchise_id, step_order, title, type, episodes, anime_id, note) VALUES ('kaguya-sama', 2, 'Kaguya-sama: Love Is War? (Season 2)', 'TV Series', '12 Episodes', NULL, 'Student council election and Ishigami sports festival arc.');
INSERT INTO franchise_watch_order (franchise_id, step_order, title, type, episodes, anime_id, note) VALUES ('kaguya-sama', 3, 'Kaguya-sama: Ultra Romantic (Season 3)', 'TV Series', '13 Episodes', NULL, 'The legendary Dual Confession and cultural festival climax.');
INSERT INTO franchise_watch_order (franchise_id, step_order, title, type, episodes, anime_id, note) VALUES ('kaguya-sama', 4, 'The First Kiss That Never Ends', 'Movie / Special', '4 Episodes (90 mins)', 'kaguya-sama', 'Crucial canon continuation exploring emotional intimacy.');
INSERT OR REPLACE INTO anime (
      id, slug, title, original_title, year, episodes, status,
      personal_rating, poster, backdrop, added_date, last_updated,
      honesty_status, filler_percentage, trending, synopsis,
      franchise_id, franchise_step_order,
      review_heading, review_paragraphs,
      source_title, source_original_title, source_author, source_type,
      source_volumes, source_publication_status, source_adaptation_status,
      source_coverage, source_notes,
      power_system_name, power_system_paragraphs,
      lesson_heading, lesson_takeaway
    ) VALUES (
      'kaguya-sama', 'kaguya-sama-love-is-war', 'Kaguya-sama: Love Is War', 'かぐや様は告らせたい ～天才たちの恋愛頭脳戦～', 2019, 37, 'Finished Airing',
      9.4, 'https://image.tmdb.org/t/p/w780/dqZENchTd7lp5zht7BdlqM7RBhD.jpg', 'https://image.tmdb.org/t/p/w1280/pBqg8G1f0M3Vw6c3qJ1iK7y5W4D.jpg', 'Jan 12, 2024', 'Sep 10, 2024',
      'watched', 0, 0, 'Two genius student council leaders are too proud to confess their feelings, turning daily high school interactions into elaborate psychological warfare to force the other to confess first.',
      'kaguya-sama', 4,
      'Peak Romantic Comedy with Genuinely Historic Payoffs', '["Most rom-com anime suffer from endless status quo stagnation, but Kaguya-sama actually evolves. The psychological mind games start as brilliant slapstick comedy, and over three seasons develop into genuine, mature emotional vulnerability.","The dual confession climax in Season 3 Ultra Romantic is one of the most satisfying romantic payoffs I have ever watched. The narrator’s comedic delivery alone makes this an essential watch."]',
      'Kaguya-sama: Love Is War', 'かぐや様は告らせたい', 'Aka Akasaka', 'Manga',
      '28 Volumes / 281 Chapters', 'Completed (2015 – 2022)', 'Partially Adapted',
      'Anime and Movie adapt up through Chapter 151 (Volume 15).', 'Chapters 152 to 281 remain available in the completed manga.',
      NULL, NULL,
      NULL, NULL
    );
INSERT OR REPLACE INTO anime_aliases (anime_id, alias) VALUES ('kaguya-sama', 'kaguya-sama');
INSERT OR REPLACE INTO anime_aliases (anime_id, alias) VALUES ('kaguya-sama', 'kaguya');
INSERT OR REPLACE INTO anime_aliases (anime_id, alias) VALUES ('kaguya-sama', 'kaguya-sama-love-is-war');
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('kaguya-sama', 'Romance');
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('kaguya-sama', 'Comedy');
INSERT OR REPLACE INTO anime_genres (anime_id, genre) VALUES ('kaguya-sama', 'Psychological');
INSERT OR REPLACE INTO anime_vibes (anime_id, vibe_id) VALUES ('kaguya-sama', 'slow-burn-romance');
INSERT OR REPLACE INTO anime_vibes (anime_id, vibe_id) VALUES ('kaguya-sama', 'beginners');
INSERT INTO anime_filler_ranges (anime_id, range, type, arc, range_order) VALUES ('kaguya-sama', '1–37', 'Canon', 'Manga Chapters 1 through 151', 1);
INSERT INTO anime_characters (anime_id, rank, name, category, role, commentary) VALUES ('kaguya-sama', 1, 'Yu Ishigami', 'Best Written', 'Student Council Treasurer', 'Grows from cynical loner into the most beloved character with one of the best redemption arcs in comedy.');
INSERT INTO anime_characters (anime_id, rank, name, category, role, commentary) VALUES ('kaguya-sama', 2, 'Kaguya Shinomiya', 'Fan Favorite', 'Vice President', 'A wealthy heiress torn between pride and genuine teenage infatuation.');